const precios = {
  comunYUTCGR: [
    { material: "SERIE 1", precio: 798 },
    { material: "SERIE 2", precio: 833 },
    { material: "SERIE 3", precio: 869 },
    { material: "SERIE 4", precio: 904 },
    { material: "SERIE 5", precio: 956 },
    { material: "SERIE 6", precio: 1010 },
    { material: "SERIE 7", precio: 1080 },
    { material: "PROMO", precio: 1205 },
    { material: "PIEL A", precio: 1277 },
    { material: "PIEL B", precio: 1378 },
    { material: "PIEL C", precio: 1552 },
    { material: "PIEL D", precio: 1753 },
  ],
  comunYUTCMA: [
    { material: "SERIE 1", precio: 827 },
    { material: "SERIE 2", precio: 862 },
    { material: "SERIE 3", precio: 898 },
    { material: "SERIE 4", precio: 935 },
    { material: "SERIE 5", precio: 990 },
    { material: "SERIE 6", precio: 1044 },
    { material: "SERIE 7", precio: 1116 },
    { material: "PROMO", precio: 1114 },
    { material: "PIEL A", precio: 1181 },
    { material: "PIEL B", precio: 1275 },
    { material: "PIEL C", precio: 1436 },
    { material: "PIEL D", precio: 1625 },
  ],
  comunYUTCME: [
    { material: "SERIE 1", precio: 877 },
    { material: "SERIE 2", precio: 915 },
    { material: "SERIE 3", precio: 955 },
    { material: "SERIE 4", precio: 955 },
    { material: "SERIE 5", precio: 1055 },
    { material: "SERIE 6", precio: 1114 },
    { material: "SERIE 7", precio: 1194 },
    { material: "PROMO", precio: 1363 },
    { material: "PIEL A", precio: 1450 },
    { material: "PIEL B", precio: 1572 },
    { material: "PIEL C", precio: 1781 },
    { material: "PIEL D", precio: 2024 },
  ],
  comunYUTMGR: [
    { material: "SERIE 1", precio: 823 },
    { material: "SERIE 2", precio: 852 },
    { material: "SERIE 3", precio: 881 },
    { material: "SERIE 4", precio: 910 },
    { material: "SERIE 5", precio: 954 },
    { material: "SERIE 6", precio: 998 },
    { material: "SERIE 7", precio: 998 },
    { material: "PROMO", precio: 1066 },
    { material: "PIEL A", precio: 1117 },
    { material: "PIEL B", precio: 1190 },
    { material: "PIEL C", precio: 1313 },
    { material: "PIEL D", precio: 1457 },
  ],
  comunYUTMGRDI: [
    { material: "SERIE 1", precio: 921 },
    { material: "SERIE 2", precio: 954 },
    { material: "SERIE 3", precio: 986 },
    { material: "SERIE 4", precio: 1019 },
    { material: "SERIE 5", precio: 1067 },
    { material: "SERIE 6", precio: 1116 },
    { material: "SERIE 7", precio: 1181 },
    { material: "PROMO", precio: 1302 },
    { material: "PIEL A", precio: 1375 },
    { material: "PIEL B", precio: 1477 },
    { material: "PIEL C", precio: 1654 },
    { material: "PIEL D", precio: 1859 },
  ],
  comunYUTMMADI: [
    { material: "SERIE 1", precio: 967 },
    { material: "SERIE 2", precio: 1000 },
    { material: "SERIE 3", precio: 1033 },
    { material: "SERIE 4", precio: 1067 },
    { material: "SERIE 5", precio: 1117 },
    { material: "SERIE 6", precio: 1167 },
    { material: "SERIE 7", precio: 1235 },
    { material: "PROMO", precio: 1344 },
    { material: "PIEL A", precio: 1418 },
    { material: "PIEL B", precio: 1521 },
    { material: "PIEL C", precio: 1696 },
    { material: "PIEL D", precio: 1902 },
  ],
  comunYUTMME: [
    { material: "SERIE 1", precio: 909 },
    { material: "SERIE 2", precio: 939 },
    { material: "SERIE 3", precio: 969 },
    { material: "SERIE 4", precio: 1000 },
    { material: "SERIE 5", precio: 1044 },
    { material: "SERIE 6", precio: 1090 },
    { material: "SERIE 7", precio: 1150 },
    { material: "PROMO", precio: 1232 },
    { material: "PIEL A", precio: 1296 },
    { material: "PIEL B", precio: 1387 },
    { material: "PIEL C", precio: 1542 },
    { material: "PIEL D", precio: 1725 },
  ],
  comunYUTMMEDI: [
    { material: "SERIE 1", precio: 1003 },
    { material: "SERIE 2", precio: 1039 },
    { material: "SERIE 3", precio: 1074 },
    { material: "SERIE 4", precio: 1109 },
    { material: "SERIE 5", precio: 1162 },
    { material: "SERIE 6", precio: 1214 },
    { material: "SERIE 7", precio: 1285 },
    { material: "PROMO", precio: 1411 },
    { material: "PIEL A", precio: 1491 },
    { material: "PIEL B", precio: 1602 },
    { material: "PIEL C", precio: 1793 },
    { material: "PIEL D", precio: 2016 },
  ],
  comunYUTMXLDI: [
    { material: "SERIE 1", precio: 1049 },
    { material: "SERIE 2", precio: 1084 },
    { material: "SERIE 3", precio: 1119 },
    { material: "SERIE 4", precio: 1155 },
    { material: "SERIE 5", precio: 1207 },
    { material: "SERIE 6", precio: 1260 },
    { material: "SERIE 7", precio: 1330 },
    { material: "PROMO", precio: 1454 },
    { material: "PIEL A", precio: 1533 },
    { material: "PIEL B", precio: 1644 },
    { material: "PIEL C", precio: 1835 },
    { material: "PIEL D", precio: 2058 },
  ],
  comunYUTMXL: [
    { material: "SERIE 1", precio: 954 },
    { material: "SERIE 2", precio: 985 },
    { material: "SERIE 3", precio: 1015 },
    { material: "SERIE 4", precio: 1045 },
    { material: "SERIE 5", precio: 1090 },
    { material: "SERIE 6", precio: 1135 },
    { material: "SERIE 7", precio: 1196 },
    { material: "PROMO", precio: 1275 },
    { material: "PIEL A", precio: 1340 },
    { material: "PIEL B", precio: 1431 },
    { material: "PIEL C", precio: 1586 },
    { material: "PIEL D", precio: 1767 },
  ],
  comunYUTRA: [
    { material: "SERIE 1", precio: 919 },
    { material: "SERIE 2", precio: 956 },
    { material: "SERIE 3", precio: 994 },
    { material: "SERIE 4", precio: 1033 },
    { material: "SERIE 5", precio: 1090 },
    { material: "SERIE 6", precio: 1147 },
    { material: "SERIE 7", precio: 1222 },
    { material: "PROMO", precio: 1390 },
    { material: "PIEL A", precio: 1473 },
    { material: "PIEL B", precio: 1589 },
    { material: "PIEL C", precio: 1789 },
    { material: "PIEL D", precio: 2021 },
  ],
  comunYUTRT: [
    { material: "SERIE 1", precio: 1270 },
    { material: "SERIE 2", precio: 1327 },
    { material: "SERIE 3", precio: 1385 },
    { material: "SERIE 4", precio: 1442 },
    { material: "SERIE 5", precio: 1529 },
    { material: "SERIE 6", precio: 1615 },
    { material: "SERIE 7", precio: 1731 },
    { material: "PROMO", precio: 1982 },
    { material: "PIEL A", precio: 2103 },
    { material: "PIEL B", precio: 2272 },
    { material: "PIEL C", precio: 2563 },
    { material: "PIEL D", precio: 2901 },
  ],
  comunYUTTGR: [
    { material: "SERIE 1", precio: 733 },
    { material: "SERIE 2", precio: 764 },
    { material: "SERIE 3", precio: 795 },
    { material: "SERIE 4", precio: 825 },
    { material: "SERIE 5", precio: 871 },
    { material: "SERIE 6", precio: 918 },
    { material: "SERIE 7", precio: 979 },
    { material: "PROMO", precio: 1114 },
    { material: "PIEL A", precio: 1181 },
    { material: "PIEL B", precio: 1275 },
    { material: "PIEL C", precio: 1436 },
    { material: "PIEL D", precio: 1625 },
  ],
  comunYUTTMA: [
    { material: "SERIE 1", precio: 759 },
    { material: "SERIE 2", precio: 791 },
    { material: "SERIE 3", precio: 823 },
    { material: "SERIE 4", precio: 855 },
    { material: "SERIE 5", precio: 903 },
    { material: "SERIE 6", precio: 950 },
    { material: "SERIE 7", precio: 1013 },
    { material: "PROMO", precio: 1151 },
    { material: "PIEL A", precio: 1221 },
    { material: "PIEL B", precio: 1319 },
    { material: "PIEL C", precio: 1487 },
    { material: "PIEL D", precio: 1682 },
  ],
};
const piezas = [
  {
    id: "None",
    title: "---Sin pieza seleccionada--",
    imageUrl: "..",
  },
  {
    id: "YUTCGRD",
    title: "YUTCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_80_DER.png",
    price: precios.comunYUTCGR,
    medida: 104,
  },
  {
    id: "YUTCGRI",
    title: "YUTCGRI Chaise longue grande (104 cm) izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_80_IZQ.png",
    price: precios.comunYUTCGR,
    medida: 104,
  },
  {
    id: "YUTCMAD",
    title: "YUTCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_90_DER.png",
    price: precios.comunYUTCMA,
    medida: 114,
  },
  {
    id: "YUTCMAI",
    title: "YUTCMAI Chaise longue maxi (114 cm) izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_90_IZQ.png",
    price: precios.comunYUTCMA,
    medida: 114,
  },
  {
    id: "YUTCMED",
    title: "YUTCMED Chaise longue mega (124 cm) dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_100_DER.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTCMEI",
    title: "YUTCMEI Chaise longue mega (124 cm) izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/CH_100_IZQ.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTMGR",
    title: "YUTMGR Módulo grande (80 cm) sin brazo",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M80_SB.png",
    price: precios.comunYUTMGR,
  },
  {
    id: "YUTMGRD",
    title: "YUTMGRD Módulo grande (104 cm) brazo dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M80_DER.png",
    price: precios.comunYUTMGRDI,
  },
  {
    id: "YUTMGRI",
    title: "YUTMGRI Módulo grande (104 cm) brazo izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M80_IZQ.png",
    price: precios.comunYUTMGRDI,
  },
  {
    id: "YUTMMAD",
    title: "YUTMMAD Módulo maxi (114 cm) brazo dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M90_DER.png",
    price: precios.comunYUTMMADI,
  },
  {
    id: "YUTMMAI",
    title: "YUTMMAI Módulo maxi (114 cm) brazo izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M90_IZQ.png",
    price: precios.comunYUTMMADI,
  },
  {
    id: "YUTMME",
    title: "YUTMME Módulo mega (100 cm) sin brazo",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M100_SB.png",
    price: precios.comunYUTMME,
  },
  {
    id: "YUTMMED",
    title: "YUTMMED Módulo mega (124 cm) brazo dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M100_DER.png",
    price: precios.comunYUTMMEDI,
  },
  {
    id: "YUTMMEI",
    title: "YUTMMEI Módulo mega (124 cm) brazo izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M100_IZQ.png",
    price: precios.comunYUTMMEDI,
  },
  {
    id: "YUTMXL",
    title: "YUTMXL Módulo XL (110 cm) sin brazo",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M110_SB.png",
    price: precios.comunYUTMXL,
  },
  {
    id: "YUTMXLD",
    title: "YUTMXLD Módulo XL (134 cm) brazo dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M110_DER.png",
    price: precios.comunYUTMXLDI,
  },
  {
    id: "YUTMXLI",
    title: "YUTMXLI Módulo XL (134 cm) brazo izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/M110_IZQ.png",
    price: precios.comunYUTMXLDI,
  },
  {
    id: "YUTRA",
    title: "YUTRA Rincón abierto (113 x 113 cm)",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/RA.png",
    price: precios.comunYUTRA,
  },
  {
    id: "YUTRTD",
    title: "YUTRTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/RT_DER.png",
    price: precios.comunYUTRT,
  },
  {
    id: "YUTRTI",
    title: "YUTRTI Rincón terminal izquierdo (108 x 205 cm)",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/RT_IZQ.png",
    price: precios.comunYUTRT,
  },
  {
    id: "YUTTGRD",
    title: "YUTTGRD Terminal grande (123 cm) dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/TER_80_DER.png",
    price: precios.comunYUTTGR,
  },
  {
    id: "YUTTGRI",
    title: "YUTTGRI Terminal grande (123 cm) izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/TER_80_IZQ.png",
    price: precios.comunYUTTGR,
  },
  {
    id: "YUTTMAD",
    title: "YUTTMAD Terminal maxi (133 cm) dcho.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/TER_90_DER.png",
    price: precios.comunYUTTMA,
  },
  {
    id: "YUTTMAI",
    title: "YUTTMAI Terminal maxi (133 cm) izqdo.",
    imageUrl: "https://francokohler.github.io/Temasdos/assets/TER_90_IZQ.png",
    price: precios.comunYUTTMA,
  },
];

const muestras = {
  brixton: [
    { img: "assets/BRIXTON/BRIXTON_10.png", nombre: "BRIXTON_10" },
    { img: "assets/BRIXTON/BRIXTON_13.png", nombre: "BRIXTON_13" },
    { img: "assets/BRIXTON/BRIXTON_16.png", nombre: "BRIXTON_16" },
    { img: "assets/BRIXTON/BRIXTON_32.png", nombre: "BRIXTON_32 " },
    { img: "assets/BRIXTON/BRIXTON_80.png", nombre: "BRIXTON_80" },
    { img: "assets/BRIXTON/BRIXTON_101.png", nombre: "BRIXTON_101" },
    { img: "assets/BRIXTON/BRIXTON_245.png", nombre: "BRIXTON_245" },
  ],
  camila: [
    { img: "assets/CAMILA/CAMILA_10.png", nombre: "CAMILA_10" },
    { img: "assets/CAMILA/CAMILA_28.png", nombre: "CAMILA_28" },
    { img: "assets/CAMILA/CAMILA_32.png", nombre: "CAMILA_32" },
    { img: "assets/CAMILA/CAMILA_51.png", nombre: "CAMILA_51" },
    { img: "assets/CAMILA/CAMILA_53.png", nombre: "CAMILA_53" },
    { img: "assets/CAMILA/CAMILA_56.png", nombre: "CAMILA_56" },
    { img: "assets/CAMILA/CAMILA_60.png", nombre: "CAMILA_60" },
    { img: "assets/CAMILA/CAMILA_90.png", nombre: "CAMILA_90" },
  ],
  montreal: [
    { img: "assets/MONTREAL/MONTREAL-01.jpg", nombre: "MONTREAL-01" },
    { img: "assets/MONTREAL/MONTREAL-02.jpg", nombre: "MONTREAL-02" },
    { img: "assets/MONTREAL/MONTREAL-03.jpg", nombre: "MONTREAL-03" },
    { img: "assets/MONTREAL/MONTREAL-04.jpg", nombre: "MONTREAL-04" },
    { img: "assets/MONTREAL/MONTREAL-05.jpg", nombre: "MONTREAL-05" },
    { img: "assets/MONTREAL/MONTREAL-06.jpg", nombre: "MONTREAL-06" },
    { img: "assets/MONTREAL/MONTREAL-07.jpg", nombre: "MONTREAL-07" },
    { img: "assets/MONTREAL/MONTREAL-08.jpg", nombre: "MONTREAL-08" },
  ],
  osaka: [
    { img: "assets/OSAKA/OSAKA-01.jpg", nombre: "OSAKA-01" },
    { img: "assets/OSAKA/OSAKA-02.jpg", nombre: "OSAKA-02" },
    { img: "assets/OSAKA/OSAKA-03.jpg", nombre: "OSAKA-03" },
    { img: "assets/OSAKA/OSAKA-04.jpg", nombre: "OSAKA-04" },
    { img: "assets/OSAKA/OSAKA-05.jpg", nombre: "OSAKA-05" },
    { img: "assets/OSAKA/OSAKA-06.jpg", nombre: "OSAKA-06" },
    { img: "assets/OSAKA/OSAKA-08.jpg", nombre: "OSAKA-08" },
  ],
  terranova: [
    { img: "assets/TERRANOVA/TERRANOVA-01.jpg", nombre: "TERRANOVA-01" },
    { img: "assets/TERRANOVA/TERRANOVA-02.jpg", nombre: "TERRANOVA-02" },
    { img: "assets/TERRANOVA/TERRANOVA-03.jpg", nombre: "TERRANOVA-03" },
    { img: "assets/TERRANOVA/TERRANOVA-04.jpg", nombre: "TERRANOVA-04" },
    { img: "assets/TERRANOVA/TERRANOVA-05.jpg", nombre: "TERRANOVA-05" },
    { img: "assets/TERRANOVA/TERRANOVA-06.jpg", nombre: "TERRANOVA-06" },
    { img: "assets/TERRANOVA/TERRANOVA-07.jpg", nombre: "TERRANOVA-07" },
    { img: "assets/TERRANOVA/TERRANOVA-08.jpg", nombre: "TERRANOVA-08" },
    { img: "assets/TERRANOVA/TERRANOVA-09.jpg", nombre: "TERRANOVA-09" },
  ],
};
