const precios = {
  comunYUTCGR: [
    { material: "SERIE 1", precio: "798" },
    { material: "SERIE 2", precio: "833" },
    { material: "SERIE 3", precio: "869" },
    { material: "SERIE 4", precio: "904" },
    { material: "SERIE 5", precio: "956" },
    { material: "SERIE 6", precio: "1.010" },
    { material: "SERIE 7", precio: "1.080" },
    { material: "Promo", precio: "1.205" },
    { material: "Piel A", precio: "1.277" },
    { material: "PIEL B", precio: "1.378" },
    { material: "PIEL C", precio: "1.552" },
    { material: "PIEL D", precio: "1.753" },
  ],
  comunYUTCMA: [
    { material: "SERIE 1", precio: "827" },
    { material: "SERIE 2", precio: "862" },
    { material: "SERIE 3", precio: "898" },
    { material: "SERIE 4", precio: "935" },
    { material: "SERIE 5", precio: "990" },
    { material: "SERIE 6", precio: "1044" },
    { material: "SERIE 7", precio: "1.116" },
    { material: "Promo", precio: "1.114" },
    { material: "Piel A", precio: "1.181" },
    { material: "PIEL B", precio: "1.275" },
    { material: "PIEL C", precio: "1.436" },
    { material: "PIEL D", precio: "1.625" },
  ],
  comunYUTCME: [
    { material: "SERIE 1", precio: "877" },
    { material: "SERIE 2", precio: "915" },
    { material: "SERIE 3", precio: "955" },
    { material: "SERIE 4", precio: "955" },
    { material: "SERIE 5", precio: "1.055" },
    { material: "SERIE 6", precio: "1.114" },
    { material: "SERIE 7", precio: "1.194" },
    { material: "Promo", precio: "1.363" },
    { material: "Piel A", precio: "1.450" },
    { material: "PIEL B", precio: "1.572" },
    { material: "PIEL C", precio: "1.781" },
    { material: "PIEL D", precio: "2.024" },
  ],
};
const piezas = [
  {
    id: "None",
    title: "---Sin pieza seleccionada--",
    imageUrl: "..",
  },
  {
    id: "YUTCGRD",
    title: "YUTCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl: "../assets/CH_80_DER.png",
    price: precios.comunYUTCGR,
  },
  {
    id: "YUTCGRI",
    title: "YUTCGRI Chaise longue grande (104 cm) izqdo.",
    imageUrl: "../assets/CH_80_IZQ.png",
    price: precios.comunYUTCGR,
  },
  {
    id: "YUTCMAD",
    title: "YUTCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl: "../assets/CH_90_DER,png",
    price: precios.comunYUTCMA,
  },
  {
    id: "YUTCMAI",
    title: "YUTCMAI Chaise longue maxi (114 cm) izqdo.",
    imageUrl: "../assets/CH_90_IZQ.png",
    price: precios.comunYUTCMA,
  },
  {
    id: "YUTCMED",
    title: "YUTCMED Chaise longue mega (124 cm) dcho.",
    imageUrl: "../assets/CH_100_DER.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTCMEI",
    title: "YUTCMEI Chaise longue mega (124 cm) izqdo.",
    imageUrl: "../assets/CH_100_IZQ.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTMGR",
    title: "YUTMGR Módulo grande (80 cm) sin brazo",
    imageUrl: "../assets/M80_SB.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMGRD",
    title: "YUTMGRD Módulo grande (104 cm) brazo dcho.",
    imageUrl: "../assets/M80_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMGRI",
    title: "YUTMGRI Módulo grande (104 cm) brazo izqdo.",
    imageUrl: "../assets/M80_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMMAD",
    title: "YUTMMAD Módulo maxi (114 cm) brazo dcho.",
    imageUrl: "../assets/M90_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMMAI",
    title: "YUTMMAI Módulo maxi (114 cm) brazo izqdo.",
    imageUrl: "../assets/M90_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMME",
    title: "YUTMME Módulo mega (100 cm) sin brazo",
    imageUrl: "../assets/M100_SB.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMMED",
    title: "YUTMMED Módulo mega (124 cm) brazo dcho.",
    imageUrl: "../assets/M100_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMMEI",
    title: "YUTMMEI Módulo mega (124 cm) brazo izqdo.",
    imageUrl: "../assets/M100_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMXL",
    title: "YUTMXL Módulo XL (110 cm) sin brazo",
    imageUrl: "../assets/M110_SB.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMXLD",
    title: "YUTMXLD Módulo XL (134 cm) brazo dcho.",
    imageUrl: "../assets/M110_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTMXLI",
    title: "YUTMXLI Módulo XL (134 cm) brazo izqdo.",
    imageUrl: "../assets/M110_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTRA",
    title: "YUTRA Rincón abierto (113 x 113 cm)",
    imageUrl: "../assets/RA.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTRTD",
    title: "YUTRTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl: "../assets/RT_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTRTI",
    title: "YUTRTI Rincón terminal izquierdo (108 x 205 cm)",
    imageUrl: "../assets/RT_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTRTI",
    title: "YUTTGRD Terminal grande (123 cm) dcho.",
    imageUrl: "../assets/TER_80_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTTGRI",
    title: "YUTTGRI Terminal grande (123 cm) izqdo.",
    imageUrl: "../assets/TER_80_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTTMAD",
    title: "YUTTMAD Terminal maxi (133 cm) dcho.",
    imageUrl: "../assets/TER_90_DER.png",
    price: 0 /*PRECIO BASE*/,
  },
  {
    id: "YUTTMAI",
    title: "YUTTMAI Terminal maxi (133 cm) izqdo.",
    imageUrl: "../assets/TER_90_IZQ.png",
    price: 0 /*PRECIO BASE*/,
  },
];
