const piezas = [
  {
    id: "YUTCGRD",
    title: "YUTCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl: "../assets/CH_80_DER.png",
    price: "4",
  },
  {
    id: "YUTCGRI",
    title: "YUTCGRI Chaise longue grande (104 cm) izqdo.",
    imageUrl: "../assets/CH_80_IZQ.png",
    price: "5",
  },
  {
    id: "YUTCMAD",
    title: "YUTCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl: "../assets/CH_90_DER,png",
    price: "5",
  },
  {
    id: "YUTCMAI",
    title: "YUTCMAI Chaise longue maxi (114 cm) izqdo.",
    imageUrl: "../assets/CH_90_IZQ.png",
    price: "5",
  },
  {
    id: "YUTCMED",
    title: "YUTCMED Chaise longue mega (124 cm) dcho.",
    imageUrl: "../assets/CH_100_DER.png",
    price: "5",
  },
  {
    id: "YUTCMEI",
    title: "YUTCMEI Chaise longue mega (124 cm) izqdo.",
    imageUrl: "../assets/CH_100_IZQ.png",
    price: "5",
  },
  {
    id: "YUTMGR",
    title: "YUTMGR Módulo grande (80 cm) sin brazo",
    imageUrl: "../assets/M80_SB.png",
    price: "5",
  },
  {
    id: "YUTMGRD",
    title: "YUTMGRD Módulo grande (104 cm) brazo dcho.",
    imageUrl: "../assets/M80_DER.png",
    price: "5",
  },
  {
    id: "YUTMGRI",
    title: "YUTMGRI Módulo grande (104 cm) brazo izqdo.",
    imageUrl: "../assets/M80_IZQ.png",
    price: "5",
  },
  {
    id: "YUTMMAD",
    title: "YUTMMAD Módulo maxi (114 cm) brazo dcho.",
    imageUrl: "../assets/M90_DER.png",
    price: "5",
  },
  {
    id: "YUTMMAI",
    title: "YUTMMAI Módulo maxi (114 cm) brazo izqdo.",
    imageUrl: "../assets/M90_IZQ.png",
    price: "5",
  },
  {
    id: "YUTMME",
    title: "YUTMME Módulo mega (100 cm) sin brazo",
    imageUrl: "../assets/M100_SB.png",
    price: "5",
  },
  {
    id: "YUTMMED",
    title: "YUTMMED Módulo mega (124 cm) brazo dcho.",
    imageUrl: "../assets/M100_DER.png",
    price: "5",
  },
  {
    id: "YUTMMEI",
    title: "YUTMMEI Módulo mega (124 cm) brazo izqdo.",
    imageUrl: "../assets/M100_IZQ.png",
    price: "5",
  },
  {
    id: "YUTMXL",
    title: "YUTMXL Módulo XL (110 cm) sin brazo",
    imageUrl: "../assets/M110_SB.png",
    price: "5",
  },
  {
    id: "YUTMXLD",
    title: "YUTMXLD Módulo XL (134 cm) brazo dcho.",
    imageUrl: "../assets/M110_DER.png",
    price: "5",
  },
  {
    id: "YUTMXLI",
    title: "YUTMXLI Módulo XL (134 cm) brazo izqdo.",
    imageUrl: "../assets/M110_IZQ.png",
    price: "5",
  },
  {
    id: "YUTRA",
    title: "YUTRA Rincón abierto (113 x 113 cm)",
    imageUrl: "../assets/RA.png",
    price: "5",
  },
  {
    id: "YUTRTD",
    title: "YUTRTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl: "../assets/RT_DER.png",
    price: "5",
  },
  {
    id: "YUTRTI",
    title: "YUTRTI Rincón terminal izquierdo (108 x 205 cm)",
    imageUrl: "../assets/RT_IZQ.png",
    price: "5",
  },
  {
    id: "YUTRTI",
    title: "YUTTGRD Terminal grande (123 cm) dcho.",
    imageUrl: "../assets/TER_80_DER.png",
    price: "5",
  },
  {
    id: "YUTTGRI",
    title: "YUTTGRI Terminal grande (123 cm) izqdo.",
    imageUrl: "../assets/TER_80_IZQ.png",
    price: "5",
  },
  {
    id: "YUTTMAD",
    title: "YUTTMAD Terminal maxi (133 cm) dcho.",
    imageUrl: "../assets/TER_90_DER.png",
    price: "5",
  },
  {
    id: "YUTTMAI",
    title: "YUTTMAI Terminal maxi (133 cm) izqdo.",
    imageUrl: "../assets/TER_90_IZQ.png",
    price: "5",
  },
];
